import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Template/Header/Header";
import "bootstrap/dist/css/bootstrap.css";
import { Container, ThemeProvider } from "react-bootstrap";
import Navbar from "@/Components/Template/Navbar/Navbar";
import Footer from "@/Components/Template/Footer/Footer";
import { ContextProvider } from "@/Context/Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ContextProvider>
      <body className={inter.className}>
        <div style={{ marginTop: "65px" }}>
          <ThemeProvider dir="rtl">
          <Header />
          <Navbar />
          {children}
          <Footer/>
          </ThemeProvider>
        </div>
      </body>
      </ContextProvider>
    </html>
  );
}
