import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Template/Header/Header";
import "bootstrap/dist/css/bootstrap.css";
import { Container } from "react-bootstrap";
import Navbar from "@/Components/Template/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ marginTop: "65px" }}>
          <Header />
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
