import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Template/Header/Header";
import "bootstrap/dist/css/bootstrap.css"
import { Container } from "react-bootstrap";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <Container>
          <Header/>
        {children}
          </Container>
        </body>
    </html>
  );
}
